### PR TITLE
FBSW-208 Moved common overlapping code from PosixShmSegment and FileShmSegment to ShmCommon

### PR DESCRIPTION
**Pull request by guptask**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/5)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/5)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[cachelib/shm/ShmCommon.h, line 149 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-Mn_gTag7taMbT4_I-c3:-Mn_gTag7taMbT4_I-c4:baioqif) ([raw file](https://github.com/pmem/cachelib/blob/fad2aafd86412c032b022ead53145bec8804b8ae/cachelib/shm/ShmCommon.h#L149)):*
> ```objc
> 
> // @throw  std::invalid_argument if the segment name is not created
> int  openImpl(const char* name, int flags, bool isFileShm = false);
> ```

I'm not sure about this but it might a bit more generic/clear to do something like this:

```
int openImp(open_func open_f, const char* name, int flags);

...

auto ret = openImpl(shm_open, name, flags);
OR
auto ret = openImpl(open, name, flags);
```

What do you think?

**Review by victoria-mcgrath — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/5)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @guptask)

___
*[cachelib/shm/FileShmSegment.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-MnbSqLEDdmb0hA9yb8F:-MnbSqLF33yE5fy_9iyi:b-1jbjg8) ([raw file](https://github.com/pmem/cachelib/blob/aa758e84498085191475e02ed6a84aa85dd8ca37/cachelib/shm/FileShmSegment.cpp#L41)):*
> ```cpp
> 
>   if (fd != -1) {
>     return fd;
> ```

I believe the preference should be to have a single return statement for each function. It improves readability and simplifies maintainability. Please consider changing to a single exit point for every function.
___
*[cachelib/shm/FileShmSegment.cpp, line 44 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-MnbT75g9K7y3U5M6RUf:-MnbT75g9K7y3U5M6RUg:b27cq63) ([raw file](https://github.com/pmem/cachelib/blob/aa758e84498085191475e02ed6a84aa85dd8ca37/cachelib/shm/FileShmSegment.cpp#L44)):*
> ```cpp
>   }
> 
>   switch (errno) {
> ```

This switch statement (and some slightly different ones) is repeated several times throughout this file. It will be better to write a function or somehow combine similar code that would do this error analysis and call it instead of copy/pasting it.

**Review by victoria-mcgrath — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/5)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @guptask)

___
*[cachelib/shm/FileShmSegment.cpp, line 266 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-MnbUopp5dhm8-Bx64RZ:-MnbUopp5dhm8-Bx64R_:b-ei34s2) ([raw file](https://github.com/pmem/cachelib/blob/aa758e84498085191475e02ed6a84aa85dd8ca37/cachelib/shm/FileShmSegment.cpp#L266)):*
> ```cpp
>   } else {
>     throw std::runtime_error(folly::sformat(
>         "Trying to get size of  segment with name {} in an invalid state",
> ```

Remove extra space after "of"

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/5)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @guptask and @victoria-mcgrath)

___
*[cachelib/shm/FileShmSegment.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-MnbSqLEDdmb0hA9yb8F:-MneFvNZ6PQsZTC33PWu:b8j7rh8) ([raw file](https://github.com/pmem/cachelib/blob/aa758e84498085191475e02ed6a84aa85dd8ca37/cachelib/shm/FileShmSegment.cpp#L41)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

I believe the preference should be to have a single return statement for each function. It improves readability and simplifies maintainability. Please consider changing to a single exit point for every function.
</blockquote></details>

I think that having return statements for such "easy" cases is fine, for me, it improves readability.

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/shm/FileShmSegment.cpp, line 41 at r1](https://reviewable.io/reviews/pmem/cachelib/5#-MnbSqLEDdmb0hA9yb8F:-MnfO-795OMxvLsaTMj-:bpp6u4w) ([raw file](https://github.com/pmem/cachelib/blob/aa758e84498085191475e02ed6a84aa85dd8ca37/cachelib/shm/FileShmSegment.cpp#L41)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think that having return statements for such "easy" cases is fine, for me, it improves readability.
</blockquote></details>

"Readability" may be subjective. Ease of maintenance and debug may be not. I looked over the rest of the code and it looks like multiple returns used all over the place. I decided to retract my original request.

**Pull request closed without merging**
