### PR TITLE
Background evictor thread

### PR DESCRIPTION
**Pull request by byrnedj**
Purpose – To increase insertion path performance, we would like to pre-emptively evict items from the current tier so that allocations may be done without needing to call an eviction.

Method – Implement background thread performing eviction for a given tier (right now this is tier 0 by default but can be extended in the future) – for each memory pool we check the classes to see if the class exceeds a preconfigured free space threshold – if the class does exceed the threshold, we calculate the number of items needed to evict in order to meet that threshold. This way the evictions occur in batch for each class – avoiding contending for the LRU lock for individual evictions.

## Results
== Test Results Without Background Evictor Thread ==
== Allocator Stats ==
Items in RAM  : 115,951
Items in NVM  : 0
Alloc Attempts: 4,311,097 Success: 84.89%
RAM Evictions : 3,518,361
Background Tier 0 Evictions : 0
Background Tier 0 Eviction Runs : 0
Cache Gets    : 4,000,000
Hit Ratio     :  44.66%
NVM Gets      :               0, Coalesced : 100.00%
NVM Puts      :               0, Success   :   0.00%, Clean   : 100.00%, AbortsFromDel   :        0, AbortsFromGet   :        0
NVM Evicts    :               0, Clean     : 100.00%, Unclean :       0, Double          :        0
NVM Deletes   :               0 Skipped Deletes: 100.00%

== Throughput for  ==
Total Ops : 4.00 million
Total sets: 2,213,563
get       :   169,688/s, success   :  44.66%
set       :    93,903/s, success   : 100.00%
del       :         0/s, found     :   0.00%

== Test Results With Background Eviction Running every 100ms - 100 allocations per class free ==
== Allocator Stats ==
Items in RAM  : 28,634
Items in NVM  : 0
Alloc Attempts: 4,422,553 Success: 63.16%
RAM Evictions : 2,657,768
Background Tier 0 Evictions : 87,098
Background Tier 0 Eviction Runs : 148
Cache Gets    : 4,000,000
Hit Ratio     :  44.36%
NVM Gets      :               0, Coalesced : 100.00%
NVM Puts      :               0, Success   :   0.00%, Clean   : 100.00%, AbortsFromDel   :        0, AbortsFromGet   :        0
NVM Evicts    :               0, Clean     : 100.00%, Unclean :       0, Double          :        0
NVM Deletes   :               0 Skipped Deletes: 100.00%

== Throughput for  ==
Total Ops : 4.00 million
Total sets: 2,225,607
get       :   224,013/s, success   :  44.36%
set       :   124,641/s, success   : 100.00%
del       :         0/s, found     :   0.00%

Improvement in GET/SET throughput is about 30% for this small test (200MB cache, 4M requests, 400K objects, normal distribution, 8 threads) - see attached configs.
[config-4GB-DRAM-4GB-DRAM-short.txt](https://github.com/pmem/CacheLib/files/8181502/config-4GB-DRAM-4GB-DRAM-short.txt)
[config-4GB-DRAM-4GB-DRAM-short-bg-evict.txt](https://github.com/pmem/CacheLib/files/8181503/config-4GB-DRAM-4GB-DRAM-short-bg-evict.txt)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/52)

### CODE REVIEW

**Comment by vinser52** [comment]
Could you please also run your tests with our normal 4GB-DRAM-4GB-PMEM config?

**Comment by byrnedj** [comment]
Updated results with the normal config after fix with item's not being properly released. About 30% improvement in throughput. 
[bg_10ms_0.001_post.txt](https://github.com/pmem/CacheLib/files/8247477/bg_10ms_0.001_post.txt)
[no_bg_post.txt](https://github.com/pmem/CacheLib/files/8247478/no_bg_post.txt)

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/52)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @byrnedj and @igchor)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 328 at r2](https://reviewable.io/reviews/pmem/cachelib/52#-MyD0hNs0uJTPPcgsrj3:-MyD0hNs0uJTPPcgsrj4:b-lj2foy) ([raw file](https://github.com/pmem/cachelib/blob/26c8eb5ee5d7838c4ad783dc125e16c0d73ee836/cachelib/allocator/CacheAllocator-inl.h#L328)):*
> ```objc
>                           config_.ccacheOptimizeStepSizePercent);
>   }
>   if (config_.poolOptimizerEnabled()) {
> ```

isn't this a duplicate of code above?
___
*[cachelib/allocator/FreeThresholdStrategy.cpp, line 39 at r2](https://reviewable.io/reviews/pmem/cachelib/52#-MyD1cGU4mfSCLZHIRJ9:-MyD1cGU4mfSCLZHIRJA:b-vnb4dn) ([raw file](https://github.com/pmem/cachelib/blob/26c8eb5ee5d7838c4ad783dc125e16c0d73ee836/cachelib/allocator/FreeThresholdStrategy.cpp#L39)):*
> ```cpp
>   size_t freeMem = mpStats.acStats.at(cid).getTotalFreeMemory() / allocSize;
> 
>   if (totalMem > 0) {
> ```

nit: probably you can just replace this whole function with: `return (double)mpStats.acStats.at(cid).getTotalFreeMemory() / (double)mpStats.acStats.at(cid).getTotalMemory()< freeThreshold_;`

You don't even need to divide by allocSize, since you have it on both sides of division operator

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/52)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[cachelib/allocator/KeepFreeStrategy.cpp, line 37 at r2](https://reviewable.io/reviews/pmem/cachelib/52#-MyD2eU335zVNyW8Frms:-MyD2eU335zVNyW8Frmt:bostcrn) ([raw file](https://github.com/pmem/cachelib/blob/26c8eb5ee5d7838c4ad783dc125e16c0d73ee836/cachelib/allocator/KeepFreeStrategy.cpp#L37)):*
> ```cpp
>     size_t totalAllocs = mpStats.acStats.at(cid).getTotalMemory() / allocSize;
>     size_t freeAllocs = mpStats.acStats.at(cid).getTotalFreeMemory() / allocSize;
>     if (totalAllocs > nKeepFree_ && freeAllocs < nKeepFree_) {
> ```

why not just `freeAllocs < nKeepFree_`?

**Review by igchor — COMMENTED** [review]
@byrnedj I think there is a compile error in some test, could you please fix it? This is because you added new function (getPoolById) and did not modify tests.

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/52#-:-MyDBTAH-8xcV_Mk4kpz:b-mb0or4)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @byrnedj and @igchor)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/52)* status: 0 of 20 files reviewed, 3 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[cachelib/allocator/BackgroundEvictor-inl.h, line 51 at r4](https://reviewable.io/reviews/pmem/cachelib/52#-MzQ9o2d-x5q1sKo5eaK:-MzQ9o2eEkLbH-wlaN9g:bttzp4o) ([raw file](https://github.com/pmem/cachelib/blob/1b4a9864514f64d6fb9858f9ae2f1d75e41f0d3a/cachelib/allocator/BackgroundEvictor-inl.h#L51)):*
> ```objc
>   } else {
>       //when an eviction for a given pid,cid at tier 0 is triggered this will be run
>       while (1) {
> ```

why is this infinite loop?

**Comment by igchor** [comment]
Now, part of: https://github.com/pmem/CacheLib/pull/90

**Pull request closed without merging**
