### PR TITLE
FBSW-208 Moved common segment code for posix and file shm segments into ShmCommon

### PR DESCRIPTION
**Pull request by guptask**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/7)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @guptask and @victoria-mcgrath)

___
*[cachelib/shm/ShmCommon.cpp, line 166 at r1](https://reviewable.io/reviews/pmem/cachelib/7#-Mo3Bmbp95f7gIFGfsdn:-Mo3Bmbp95f7gIFGfsdo:b-7gon8x) ([raw file](https://github.com/pmem/cachelib/blob/f419c747626e8b4b223154ec8c7462b0501a7218/cachelib/shm/ShmCommon.cpp#L166)):*
> ```cpp
>     util::throwSystemError(errno, "invalid fd");
>   }
>   return fd;
> ```

Why did you remove the switch for errno? I think the behavior might be different after this change.

**Review by guptask — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor and @victoria-mcgrath)

___
*[cachelib/shm/ShmCommon.cpp, line 166 at r1](https://reviewable.io/reviews/pmem/cachelib/7#-Mo3Bmbp95f7gIFGfsdn:-Mo55PyS97yPuyoZbblg:bqqei0v) ([raw file](https://github.com/pmem/cachelib/blob/f419c747626e8b4b223154ec8c7462b0501a7218/cachelib/shm/ShmCommon.cpp#L166)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why did you remove the switch for errno? I think the behavior might be different after this change. 
</blockquote></details>

Reverted to the errno switch case handling

**Review by igchor — COMMENTED** [review]
:lgtm:, but I would like to wait with merging this until https://github.com/pmem/CacheLib/pull/6 and https://github.com/pmem/CacheLib/pull/2 (which contains some fixes for tests) is merged. it would be good to verify if all the tests are passing on CI for this change.

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7#-:-Mo84dihD_L5Nnm6ccAc:b-j686mo)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @victoria-mcgrath)

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @guptask and @victoria-mcgrath)

___
*[cachelib/shm/FileShmSegment.cpp, line 219 at r4](https://reviewable.io/reviews/pmem/cachelib/7#-Monk8700gOsD40_zMfH:-Monk8700gOsD40_zMfI:b-ltg25x) ([raw file](https://github.com/pmem/cachelib/blob/becfc35e235bd68e676576b717db7d1e874767bc/cachelib/shm/FileShmSegment.cpp#L219)):*
> ```cpp
> 
> int FileShmSegment::createNewSegment(const std::string& name) {
>   constexpr static int createFlags = O_RDWR | O_CREAT | O_EXCL;
> ```

why you removed constexpr static?
___
*[cachelib/shm/ShmCommon.h, line 47 at r4](https://reviewable.io/reviews/pmem/cachelib/7#-MonjtY-6zIVab0NT12r:-MonjtY-6zIVab0NT12s:b7slcur) ([raw file](https://github.com/pmem/cachelib/blob/b1e197fd5deec99f2f9844653498bd55625efae8/cachelib/shm/ShmCommon.h#L47)):*
> ```objc
> };
> 
> // TODO(SHM_FILE): maybe we could use this inside the Tier Config class?
> ```

this should be removed

**Review by victoria-mcgrath — APPROVED** [review]
> Reviewed 4 of 4 files at r2, 3 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7)* status: all files reviewed, 2 unresolved discussions (waiting on @guptask)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/7#-:-MorQcZI0dI2EQeGXv0P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @guptask)

**Pull request merged**
