### PR TITLE
[Upstreaming] Added memory mapped file support

### PR DESCRIPTION
**Pull request by guptask**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/63)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
@guptask Can you please cleanup commits and add some meaningful messages to them?

Also I think we are still missing support for temp shm mappings: https://github.com/pmem/CacheLib/blob/develop/cachelib/allocator/TempShmMapping.h as described in this issue:https://github.com/pmem/CacheLib/issues/26

We can probably send this patch to Meta as is and work on temp mapping separatly 

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/63#-:-N0VZm7B-8FDVwheLQWd:b-w0lkq5)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @guptask)

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocator.h` line 1196 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19ssqvCgoUIRamuDjA:-N19ssqvCgoUIRamuDjB:b-obxj85) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator.h#L1196)):*
> ```objc
>   static bool cleanupStrayShmSegments(
>       const std::string& cacheDir, bool posix
>       /*TODO: const std::vector<CacheMemoryTierConfig>& config = {} */);
> ```

Please consider using the type defined in CacheAllocatorConfg instead, e.g. CacheAllocatorConfig<AllocatorT>::MemoryTierConfigs

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 95 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19ti-BCp4keFzksSUZ:-N19ti-BCp4keFzksSU_:bvxa61x) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator-inl.h#L95)):*
> ```objc
>   initCommon(false);
>   shmManager_->removeShm(detail::kShmInfoName,
>                          PosixSysVSegmentOpts(config_.usePosixShm));
> ```

Please consider calling the getter CacheAllocatorConfig::isUsingPosixShm() everywhere where you need to use usePosixShm.

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 71 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19u-Th7SrHL09qYCcS:-N19u-Th7SrHL09qYCcT:b-6jtsj6) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator-inl.h#L71)):*
> ```objc
>                           ShmSegmentOpts(config_.accessConfig.getPageSize(),
>                                          false,
>                                          config_.usePosixShm))
> ```

Would it make sense to use last two values as defaults for the last  two parameters? Might help minimize the total number of changes .

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 3530 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19zWEO2VFDA5uKgqHt:-N19zWEO2VFDA5uKgqHu:b-g7kfo9) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator-inl.h#L3530)):*
> ```objc
>     //   ShmManager::removeByName(cacheDir, tierShmName,
>     //   config_.memoryTiers[i].opts);
>     // }
> ```

Does thgis code need to be here? If yes, could you clean up the comment so it makes more sense in the absence contxet?

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/TempShmMapping.cpp` line 38 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19zr0H3dRZI2EbPW9-:-N19zr0H3dRZI2EbPW90:b-jgg932) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/TempShmMapping.cpp#L38)):*
> ```cpp
>     if (addr_) {
>       shmManager_->removeShm(detail::kTempShmCacheName.str(),
>                              PosixSysVSegmentOpts(false /* posix */));
> ```

Make it false by default?

**Comment by victoria-mcgrath** [comment]
*[`cachelib/shm/PosixShmSegment.h` line 96 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N1A2B8k6spB3v2-0IS8:-N1A2B8k6spB3v2-0IS9:b-a26nz3) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/shm/PosixShmSegment.h#L96)):*
> ```objc
> 
>   // returns the key type corresponding to the given name.
>   static std::string createKeyForName(const std::string& name) noexcept;
> ```

I was unable to find any code in your changes which required this method to be changed to public. Could you double check please?

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocator-inl.h` line 95 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19ti-BCp4keFzksSUZ:-N1A47cH35PBAGa3BFKY:bns68pc) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator-inl.h#L95)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

Please consider calling the getter CacheAllocatorConfig::isUsingPosixShm() everywhere where you need to use usePosixShm.
</blockquote></details>

As A general observation, I am not sure I fully understand why we keep sending posix/non-posix as a parameter to many methods instead of setting this once per object and then just accessing it as a member.

**Review by victoria-mcgrath — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 6 of 16 files at r4, 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/63)* status: all files reviewed, 6 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/CacheAllocator-inl.h` line 71 at r5](https://reviewable.io/reviews/pmem/cachelib/63#-N19u-Th7SrHL09qYCcS:-N19ywB-AJ3-diNlAKkN:b-vnm4ob) ([raw file](https://github.com/pmem/cachelib/blob/ffec15f54441755f08909d1a67c4e8d98345997e/cachelib/allocator/CacheAllocator-inl.h#L71)):*
> minimize 
reduce

**Pull request closed without merging**
