### PR TITLE
[Upstreaming] Added per pool per class used size metrics

### PR DESCRIPTION
**Pull request by guptask**
This per pool size statistics reports the current size of each memory pool. Existing implementation does not report this statistic accurately. `allocAttempts - allocFailed - regularItemsEvictions - chainedItemsEvictions won't report this value accurately because pool size grows in multiples of block sizes. This statistics will be reported in the final report generated by cachebench.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/70)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/70)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`cachelib/allocator/tests/AllocatorHitStatsTest.h` line 398 at r1](https://reviewable.io/reviews/pmem/cachelib/70#-N1mwt4R75UILcFdRc6j:-N1mwt4R75UILcFdRc6k:buxv1qx) ([raw file](https://github.com/pmem/cachelib/blob/4090a0b12ffd59fd943a1ca291cb2d9357464fd2/cachelib/allocator/tests/AllocatorHitStatsTest.h#L398)):*
> ```objc
>     ASSERT_EQ(globalCacheStats.poolUsedSize.size(),
>               MemoryPoolManager::kMaxPools);
>     ASSERT_EQ(4521459712, globalCacheStats.poolUsedSize[0]);
> ```

please calculate this value based on slab size

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/70#-:-N2Y41zvCVLAZurbIn24:bnfp4nl)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`cachelib/allocator/CacheAllocator.h` line 1119 at r2](https://reviewable.io/reviews/pmem/cachelib/70#-N2Y2pMF3K1-Z5ato1xx:-N2Y2pMF3K1-Z5ato1xy:b-hao6kz) ([raw file](https://github.com/pmem/cachelib/blob/84f4954caabe91c75830a5be8ecc7b775ceeddde/cachelib/allocator/CacheAllocator.h#L1119)):*
> ```objc
>   bool isOnShm() const noexcept { return isOnShm_; }
> 
>   ClassId getAllocClassId(PoolId pid,
> ```

I'm not sure if Meta will be OK with adding such functions. Can't we use some existing ones? Some of the tests are also marked as friends of this class, so maybe we could use that?

**Comment by guptask** [comment]
*[`cachelib/allocator/CacheAllocator.h` line 1119 at r2](https://reviewable.io/reviews/pmem/cachelib/70#-N2Y2pMF3K1-Z5ato1xx:-N2oxQdn54KudsY-N9Mh:bpga7dt) ([raw file](https://github.com/pmem/cachelib/blob/84f4954caabe91c75830a5be8ecc7b775ceeddde/cachelib/allocator/CacheAllocator.h#L1119)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if Meta will be OK with adding such functions. Can't we use some existing ones? Some of the tests are also marked as friends of this class, so maybe we could use that?
</blockquote></details>

We can raise the PR as it is here and see what Meta has to say about it. I think having an API approach is cleaner.

**Comment by guptask** [comment]
*[`cachelib/allocator/tests/AllocatorHitStatsTest.h` line 398 at r1](https://reviewable.io/reviews/pmem/cachelib/70#-N1mwt4R75UILcFdRc6j:-N2oy_MuE5aW1LPFvfm-:b-2wngc7) ([raw file](https://github.com/pmem/cachelib/blob/4090a0b12ffd59fd943a1ca291cb2d9357464fd2/cachelib/allocator/tests/AllocatorHitStatsTest.h#L398)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please calculate this value based on slab size
</blockquote></details>

I didn't understand your point. This check was pre-existing.

**Pull request closed without merging**
