### PR TITLE
FBSW-211 Enable new MemoryTierCacheConfig API in CacheBench

### PR DESCRIPTION
**Pull request by victoria-mcgrath**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/9)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
LGTM, just one question, which CacheAllocator constructor is used by Cachebench?

```
  explicit CacheAllocator(Config config);
  CacheAllocator(SharedMemNewT, Config config);
  CacheAllocator(SharedMemAttachT, Config config);
```

In my PR, I only enabled the last two. If Cachebench is using the first one, is there any easy way to change it?

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9#-:-Mo3CavR9ezzOlCoylCd:boob4g8)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor and @victoria-mcgrath)

___
*[cachelib/cachebench/test_configs/simple_tiers_test.json, line 8 at r1](https://reviewable.io/reviews/pmem/cachelib/9#-Mo3CXhk2vLyo3F9mXpm:-Mo3CXhk2vLyo3F9mXpn:b48bmp9) ([raw file](https://github.com/pmem/cachelib/blob/e2c5bc19487768c3f5268f1eb6a4202e09c855d4/cachelib/cachebench/test_configs/simple_tiers_test.json#L8)):*
> ```JSON
>       {
>         "ratio": 1,
>         "file": "/tmp/memory-mapped-tier" 
> ```

nit: unnecessary whitespaces at the end
___
*[cachelib/cachebench/test_configs/simple_tiers_test.json, line 18 at r1](https://reviewable.io/reviews/pmem/cachelib/9#-Mo3CV2QEbfD63Q-HaXn:-Mo3CV2QEbfD63Q-HaXo:b8ic1yq) ([raw file](https://github.com/pmem/cachelib/blob/e2c5bc19487768c3f5268f1eb6a4202e09c855d4/cachelib/cachebench/test_configs/simple_tiers_test.json#L18)):*
> ```JSON
>   },
>   "test_config" : {
>       
> ```

nit: unnecessary whitespaces
___
*[cachelib/cachebench/test_configs/simple_tiers_test.json, line 22 at r1](https://reviewable.io/reviews/pmem/cachelib/9#-Mo3CYomAQyuBAGi01_o:-Mo3CYomAQyuBAGi01_p:b8ic1yq) ([raw file](https://github.com/pmem/cachelib/blob/e2c5bc19487768c3f5268f1eb6a4202e09c855d4/cachelib/cachebench/test_configs/simple_tiers_test.json#L22)):*
> ```JSON
>       "numThreads" : 32,
>       "numKeys" : 1000000,
>       
> ```

nit: unnecessary whitespaces

**Comment by victoria-mcgrath** [comment]
> CacheAllocator
I set breakpoints to all three and ran simple_tiers_test.json - the first constructor from your list was called. However, if cacheDir wasn't empty, then the second one would've been called:
``` 
// cachelib/cachebench/cache/Cache-inl.h:258
  if (!cacheDir.empty()) {
    allocatorConfig_.cacheDir = cacheDir;
    cache_ =
        std::make_unique<Allocator>(Allocator::SharedMemNew, allocatorConfig_);
  } else {
    cache_ = std::make_unique<Allocator>(allocatorConfig_);
  }
```
cacheDir above is a method's argument which defaults to "", calling method (cachelib/cachebench/runner/CacheStressor.h:96) doesn't set it (relies on default value). 

Thoughts?

**Review by igchor — COMMENTED** [review]
@victoria-mcgrath can't we set the cacheDir from json config file? Is there already support for setting cacheDir?

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9#-:-MoXqaXW1cjpFvo5l4XD:bs7zrgj)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor and @victoria-mcgrath)

**Comment by victoria-mcgrath** [comment]
Yes, I added support for cacheDir. Checkout my most recent changes - the updated code and sample JSON lead to the call of one of the supported constructors.

**Review by igchor — COMMENTED** [review]
Ok, I see, I think it's, just please take a look at comments below

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9#-:-MoZO5Ob8XAtdzdESxja:b-h00gas)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @igchor and @victoria-mcgrath)

___
*[cachelib/cachebench/cache/Cache-inl.h, line 98 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZPk8o2LtdO3HB0Lvg:-MoZPk8o2LtdO3HB0Lvh:b-p80zt6) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L98)):*
> ```objc
> 
>   if (!cacheDir.empty()) {
>     allocatorConfig_.cacheDir = cacheDir;
> ```

I think you should also call enableCachePersistence here, instead of just assigning this value directly.
___
*[cachelib/cachebench/cache/Cache-inl.h, line 100 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZQTYC-qgDLjmozr-4:-MoZQTYC-qgDLjmozr-5:b7c0pbu) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L100)):*
> ```objc
>     allocatorConfig_.cacheDir = cacheDir;
>   } else if (!config_.persistedCacheDir.empty()) {
>       allocatorConfig_.enableCachePersistence(config_.persistedCacheDir);
> ```

I would rename this persistedCacheDir to cacheDir for consistency.

We could probably even consider removing this cacheDir parameter to the function and just have it in json config maybe?
___
*[cachelib/cachebench/util/CacheConfig.h, line 44 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZRU9ZBIXo4LcEm90D:-MoZRU9ZBIXo4LcEm90E:b-eufkfp) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/util/CacheConfig.h#L44)):*
> ```objc
> };
> 
> struct MemoryTierConfig : public JSONConfig {
> ```

Hm, is there a way to avoid duplicating MemoryTierCacheConfig? Why can't we just keep MemoryTierCacheConfig directly in CacheConfig?
___
*[cachelib/cachebench/util/CacheConfig.cpp, line 98 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZR2Dv4wNaeeXb5b23:-MoZR2Dv4wNaeeXb5b24:b-i1puxh) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/util/CacheConfig.cpp#L98)):*
> ```cpp
>   JSONSetVal(configJson, persistedCacheDir);
>   JSONSetVal(configJson, usePosixShm);
>   if (configJson.count("memoryTiers")) {
> ```

nit: this if seems unnecessary (the loop below should work even for size == 0, right?

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/cachebench/cache/Cache-inl.h, line 98 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZPk8o2LtdO3HB0Lvg:-MoZuKDT3q55QTFpsSu2:b-mpyznc) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L98)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think you should also call enableCachePersistence here, instead of just assigning this value directly.
</blockquote></details>

The original version of this code didn't call enableCachePersistence in this case and I decided to keep it the same. Do you think I should try changing it not knowing what I might be breaking?

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/cachebench/cache/Cache-inl.h, line 100 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZQTYC-qgDLjmozr-4:-MoZul8R-LOdlw2m8skA:b-h1bixm) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L100)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I would rename this persistedCacheDir to cacheDir for consistency.

We could probably even consider removing this cacheDir parameter to the function and just have it in json config maybe?
</blockquote></details>

I find cacheDir identifier is confusing when file-baked memory is used. cacheDir here refers to a directory where cache will be persisted at shutdown. Please confirm you still feel that I  should use cacheDir here.

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/cachebench/util/CacheConfig.h, line 44 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZRU9ZBIXo4LcEm90D:-MoZvFTcAtTmfwShi5Xj:b-38kr87) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/util/CacheConfig.h#L44)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Hm, is there a way to avoid duplicating MemoryTierCacheConfig? Why can't we just keep MemoryTierCacheConfig directly in CacheConfig?
</blockquote></details>

This is how other settings are being handled and I repeated the approach for consistency. If I were to change it the way you're suggesting, I'd have to modify MemoryTierCacheConfig, by allowing default constructor, for example.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor and @victoria-mcgrath)

___
*[cachelib/cachebench/cache/Cache-inl.h, line 98 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZPk8o2LtdO3HB0Lvg:-MocduZW5SNcEsIw71Ng:b-44wymz) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L98)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

The original version of this code didn't call enableCachePersistence in this case and I decided to keep it the same. Do you think I should try changing it not knowing what I might be breaking?
</blockquote></details>

I think we should be consistent - either do the assignment for both cases or call enableCachePersistence for both cases (there's no reason to do it differently, right?) From what I see, calling enableCachePersistence() should have the same behavior here, but would allow for better encapsulation, so yes, I'd change the old version also
___
*[cachelib/cachebench/cache/Cache-inl.h, line 100 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZQTYC-qgDLjmozr-4:-Mocct4B0bZV-J1NXB6-:bi60dcp) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/cache/Cache-inl.h#L100)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

I find cacheDir identifier is confusing when file-baked memory is used. cacheDir here refers to a directory where cache will be persisted at shutdown. Please confirm you still feel that I  should use cacheDir here.
</blockquote></details>

Right, I was thinking about consistency with the CacheAllocatorConfig (it's member is still called cacheDir) but I think you are right, persistedCacheDir might be a better name in general. I think you can keep it as it is.
___
*[cachelib/cachebench/test_configs/simple_tiers_test.json, line 22 at r1](https://reviewable.io/reviews/pmem/cachelib/9#-Mo3CYomAQyuBAGi01_o:-MoceLzF7XhgpyyAR3le:bb8m28k) ([raw file](https://github.com/pmem/cachelib/blob/e2c5bc19487768c3f5268f1eb6a4202e09c855d4/cachelib/cachebench/test_configs/simple_tiers_test.json#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: unnecessary whitespaces
</blockquote></details>

there is still some whitespace here
___
*[cachelib/cachebench/util/CacheConfig.h, line 44 at r2](https://reviewable.io/reviews/pmem/cachelib/9#-MoZRU9ZBIXo4LcEm90D:-MoceVyAB8g2C6JUzHuz:bn7dmcp) ([raw file](https://github.com/pmem/cachelib/blob/ab37ac701693e7c3ec8cdc3c45d4cabf2ecf952f/cachelib/cachebench/util/CacheConfig.h#L44)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

This is how other settings are being handled and I repeated the approach for consistency. If I were to change it the way you're suggesting, I'd have to modify MemoryTierCacheConfig, by allowing default constructor, for example.
</blockquote></details>

But for other settings, they are adding some benchmarking-specific options, right? It's not just a copy-paste. 

Why do we need a default ctor? If we would keep a vector of MemoryTierCacheConfigs it should not be necessary I believe (just copy or move ctor should be available)

**Review by vinser52 — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @igchor, @victoria-mcgrath, and @vinser52)

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/cachebench/test_configs/simple_tiers_test.json, line 22 at r1](https://reviewable.io/reviews/pmem/cachelib/9#-Mo3CYomAQyuBAGi01_o:-MoklDFW6vBa4Wf053WC:bb6un1j) ([raw file](https://github.com/pmem/cachelib/blob/e2c5bc19487768c3f5268f1eb6a4202e09c855d4/cachelib/cachebench/test_configs/simple_tiers_test.json#L22)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

there is still some whitespace here
</blockquote></details>

Done

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @igchor, @victoria-mcgrath, and @vinser52)

___
*[cachelib/allocator/CacheAllocatorConfig.h, line 559 at r8](https://reviewable.io/reviews/pmem/cachelib/9#-MonPdHf0dR1HTbHDhrB:-MonPdHf0dR1HTbHDhrC:bc5nwi1) ([raw file](https://github.com/pmem/cachelib/blob/467cf2ad98411a427cc9841f9ed2e258a345c807/cachelib/allocator/CacheAllocatorConfig.h#L559)):*
> ```objc
> 
>   // Configuration for memory tiers.
>   MemoryTierConfigs memoryTierConfigs;
> ```

This should not be here (perhaps rebase went wrong?).

memoryTierConfigs is already declared a few lines below

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/9#-:-Moo-7E_AZRLLfkmHh_N:bnfp4nl)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @igchor, @victoria-mcgrath, and @vinser52)

**Pull request merged**
