### PR TITLE
Multi-tier support exploration

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)

### CODE REVIEW

**Review by guptask — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[cachelib/allocator/Cache.h, line 261 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuIFRR6ZTGUJN8wzKl:-MpuIFRR6ZTGUJN8wzKm:b-anpvpc) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/Cache.h#L261)):*
> ```objc
>   unsigned getNumTiers() const;
> 
>   unsigned numTiers;
> ```

this should be renamed to numTiers_ or m_numTiers. I'm not sure about the convention to follow since cachelib doesn't seem to adhere strictly to one convention. Also you can assign default value of 1 to this variable even though your CacheBase constructor change does address it.
___
*[cachelib/allocator/CacheAllocator.h, line 588 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuK7rG2gFO7lWRKPYw:-MpuK7rG2gFO7lWRKPYx:bodp9xi) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator.h#L588)):*
> ```objc
>   //
>   // @throw std::invalid_argument if the poolId is invalid
>   void overridePoolConfig(TierId tid, PoolId pid, const MMConfig& config);
> ```

this is more of a design thought - we can bit pack the tier id and pool id together. It has been used in multiple places. That would make the pool id unique.
___
*[cachelib/allocator/CacheAllocator.h, line 1283 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuLLD6-OV2oPvJwTnM:-MpuLLD6-OV2oPvJwTnN:b-eyipx6) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator.h#L1283)):*
> ```objc
>   // @return true  If the move was completed, and the containers were updated
>   //               successfully.
>   bool moveRegularItemOnEviction(Item& oldItem, ItemHandle& newItemHdl);
> ```

just a thought - how much impact does memcpy have here ?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 4 unresolved discussions (waiting on @igchor)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 1792 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MqLklDi--kSVZluDuXD:-MqLklDi--kSVZluDuXE:b-rjkjba) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator-inl.h#L1792)):*
> ```objc
> CacheAllocator<CacheTrait>::getTierId(const Item& item) const {
>   // TODO: add tierID member to the Item or look at the
>   // item.getMemory() and compare it with all the tier allocators
> ```

We need to decide how to implement this functionality. There are a lot of places where it is used, but it is not implemented yet.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: 6 of 11 files reviewed, 4 unresolved discussions (waiting on @guptask and @vinser52)

___
*[cachelib/allocator/Cache.h, line 261 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuIFRR6ZTGUJN8wzKl:-MqOg4VO8NY6iZ0bF4RB:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/Cache.h#L261)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

this should be renamed to numTiers_ or m_numTiers. I'm not sure about the convention to follow since cachelib doesn't seem to adhere strictly to one convention. Also you can assign default value of 1 to this variable even though your CacheBase constructor change does address it.
</blockquote></details>

Done.
___
*[cachelib/allocator/CacheAllocator.h, line 588 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuK7rG2gFO7lWRKPYw:-MqOXMqa2AkGtyCJmUnq:b-ck23wb) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator.h#L588)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

this is more of a design thought - we can bit pack the tier id and pool id together. It has been used in multiple places. That would make the pool id unique.
</blockquote></details>

We thought about this but it would make the API somewhat inconsistent - in some places we would use PoolId as both pool and tier descriptor and in others (e.g. in public API) we would only be interested in Pool id.
___
*[cachelib/allocator/CacheAllocator.h, line 1283 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MpuLLD6-OV2oPvJwTnM:-MqOX_HZ89B6L7omk78t:b-nd5aca) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator.h#L1283)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

just a thought - how much impact does memcpy have here ?
</blockquote></details>

That's  a good question - I don't know right now but it might be useful to collect some perf/vtune data (we just need some workload)
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1792 at r2](https://reviewable.io/reviews/pmem/cachelib/12#-MqLklDi--kSVZluDuXD:-MqOg3unEBxQMpSOfTFI:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/341a94b417d4c38f62702446f58e86502a8f4115/cachelib/allocator/CacheAllocator-inl.h#L1792)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

We need to decide how to implement this functionality. There are a lot of places where it is used, but it is not implemented yet.
</blockquote></details>

Done.

**Review by vinser52 — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 1 of 2 files at r2, 2 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 16 unresolved discussions (waiting on @guptask and @igchor)

___
*[cachelib/allocator/CacheAllocator.h, line 629 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU6vqZ6s8XESbaspkd:-MqU6UB70XmZYpljHMzu:bse4ncs) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L629)):*
> ```objc
>   //          smaller than _bytes_
>   // @throw   std::invalid_argument if the poolId is invalid.
>   // TODO: should call shrinkPool for specific tier?
> ```

Is this TODO still relevant? We call currentTier() inside implementation. Another question can this method be called by user? If so, it is a possible issue because the user should not set currentTier.
___
*[cachelib/allocator/CacheAllocator.h, line 640 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU7MLe04owW9UBtiuZ:-MqU6nByEh1sorNEi28g:b-atbwyy) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L640)):*
> ```objc
>   //            bytes were not available.
>   // @throw     std::invalid_argument if the poolId is invalid.
>   // TODO: should call growPool for specific tier?
> ```

The same comment as above
___
*[cachelib/allocator/CacheAllocator.h, line 1609 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU87gE4q6LPyK922Io:-MqU87gE4q6LPyK922Ip:bs0zfob) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1609)):*
> ```objc
>     // detection.
>     folly::annotate_ignore_thread_sanitizer_guard g(__FILE__, __LINE__);
>     allocator_[0 /* TODO */]->forEachAllocation(std::forward<Fn>(f));
> ```

Should we fix this TODO.
___
*[cachelib/allocator/CacheAllocator.h, line 1676 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8GBo2M-kyA6VDSr6:-MqU8GBo2M-kyA6VDSr7:bs0zfob) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1676)):*
> ```objc
> 
>   typename Item::PtrCompressor createPtrCompressor() const {
>     return allocator_[0 /* TODO */]->createPtrCompressor<Item>();
> ```

Should we fix this TODO.
___
*[cachelib/allocator/CacheAllocator.h, line 1754 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8JCSBbPFTL94WjI4:-MqU8JCSBbPFTL94WjI5:b-yke7uj) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1754)):*
> ```objc
> 
>   TierId currentTier() const {
>     return 0; // TODO
> ```

I thoughts you already implemented this function.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1476 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU9VJN6pqnqTde4z9U:-MqU9VJN6pqnqTde4z9V:bhh1htn) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L1476)):*
> ```objc
> typename CacheAllocator<CacheTrait>::ItemHandle
> CacheAllocator<CacheTrait>::advanceIteratorAndTryEvictRegularItem(
>     TierId tid, PoolId pid, MMContainer& sourceMMContainer, EvictionIterator& itr) {
> ```

why we renamed `mmContainer` -> `sourceMMContainer`
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1973 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUA2bI-nDUvv2Yba4f:-MqUA2bI-nDUvv2Yba4g:b-udfdky) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L1973)):*
> ```objc
> typename CacheAllocator<CacheTrait>::ItemHandle
> CacheAllocator<CacheTrait>::getSampleItem() {
>   // TODO: is using random tier a good idea?
> ```

I think it is OK since this method is called only by test. But let's keep the TODO comment to discuss it with Facebook folks.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 2200 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUAbwl72fb9EO60-AO:-MqUAbwl72fb9EO60-AP:b71krhx) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L2200)):*
> ```objc
>   PoolId pid = 0;
>   for (TierId tid = 0; tid < numTiers_; tid++) {
>     // TODO: adjust size per tier
> ```

With Victoria's changes we should be able t adjust the size based on config params, isn't it?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3169 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBPDH6iOkfYlnYal0:-MqUBPDH6iOkfYlnYal1:b-boqzwh) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3169)):*
> ```objc
>   auto serializeMMContainers = [](MMContainers& mmContainers) {
>     MMSerializationTypeContainer state;
>     for (unsigned int i = 0; i < mmContainers[0 /* TODO */].size(); ++i) {
> ```

Should we do it for each tier?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3189 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBTWbCJ0Iq00Ip9Ho:-MqUBTWbCJ0Iq00Ip9Hp:b-v9j8oc) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3189)):*
> ```objc
> 
>   AccessSerializationType accessContainerState = accessContainer_->saveState();
>   // TODO: foreach allocator
> ```

Why we haven't implemented it?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3253 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBd8V8mWMycodeUku:-MqUBd8V8mWMycodeUkv:bjwavtk) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3253)):*
> ```objc
>   shmManager_.reset();
> 
>   // TODO: save per-tier state
> ```

The same comment as above.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3660 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBiYzDjos_gy6vS4-:-MqUBiYzDjos_gy6vS40:b-6ej45v) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3660)):*
> ```objc
>       ShmManager::cleanup(cacheDir, posix);
> 
>       // TODO: cleanup per-tier state
> ```

Should we implement it?
___
*[cachelib/allocator/memory/Slab.h, line 56 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBr1PCEIcuRovx5Pu:-MqUBr1PCEIcuRovx5Pv:b40lfpi) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/memory/Slab.h#L56)):*
> ```objc
> // it has a different type than PoolId and ClassID
> // to allow overloads
> using TierId = uint8_t;
> ```

Since we use your trick with `currentTier()`, do we need the different types for `TierId` and `PoolId`

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: 10 of 12 files reviewed, 16 unresolved discussions (waiting on @guptask, @igchor, and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 629 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU6vqZ6s8XESbaspkd:-MqUr17e6pNX8bemW5ul:brha7ni) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L629)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Is this TODO still relevant? We call currentTier() inside implementation. Another question can this method be called by user? If so, it is a possible issue because the user should not set currentTier.
</blockquote></details>

Yeah, this can be called by the user so I think this is still relevant - should this function shrink pool on specific tier or on all tiers at once?
___
*[cachelib/allocator/CacheAllocator.h, line 640 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU7MLe04owW9UBtiuZ:-MqUrvrcEgR4zLIFb5D_:b3kqx) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L640)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

The same comment as above
</blockquote></details>

.
___
*[cachelib/allocator/CacheAllocator.h, line 1609 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU87gE4q6LPyK922Io:-MqVHwrO813Dn98S1Ebn:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1609)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we fix this TODO.
</blockquote></details>

Done.
___
*[cachelib/allocator/CacheAllocator.h, line 1754 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8JCSBbPFTL94WjI4:-MqUsBEL3C0_s0gFmHCC:bn648fx) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1754)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I thoughts you already implemented this function.
</blockquote></details>

So, this function is used for methods which can be called by a user/background workers where use/bg worker must have per-tier knowledge. This is the problem I raised some time ago: how we can expose the statistics/operations for different tiers.

There is no good answer for that right now, so for this PR I have not implemented this correctly (this is not really needed for benchmarks, unless we are relying on bg workers).

I have this hack implementation which allows setting currentTier by user/bg worker but this is not needed for corectness for now (at least I think so)
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1476 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU9VJN6pqnqTde4z9U:-MqVIQypBSLqa_bCadVI:bto1fdl) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L1476)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

why we renamed `mmContainer` -> `sourceMMContainer`
</blockquote></details>

Done. It was remeinder of the previous implementation.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1973 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUA2bI-nDUvv2Yba4f:-MqUzm6X9siB2Julj3kt:b32w1t) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L1973)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I think it is OK since this method is called only by test. But let's keep the TODO comment to discuss it with Facebook folks.
</blockquote></details>

Ok
___
*[cachelib/allocator/CacheAllocator-inl.h, line 2200 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUAbwl72fb9EO60-AO:-MqVK15VAMhg_gORSFUa:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L2200)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

With Victoria's changes we should be able t adjust the size based on config params, isn't it?
</blockquote></details>

Done.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3169 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBPDH6iOkfYlnYal0:-MqV-J9BAcnyzI9ZMwf6:b-2d361y) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3169)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we do it for each tier?
</blockquote></details>

Yes, most probably, but this is not so critical I believe - this is for serialization.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3189 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBTWbCJ0Iq00Ip9Ho:-MqV0sDJ6_p5oX4d0EhN:b-4gkqio) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3189)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why we haven't implemented it?
</blockquote></details>

I skipped the things which are not so important - like serialization
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3253 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBd8V8mWMycodeUku:-MqV0zY8ATFX6FuR2psi:b3kqx) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3253)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

The same comment as above.
</blockquote></details>

.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3660 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBiYzDjos_gy6vS4-:-MqV1-oS7odL0JZz5RZ9:b3kqx) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3660)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we implement it?
</blockquote></details>

.
___
*[cachelib/allocator/memory/Slab.h, line 56 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBr1PCEIcuRovx5Pu:-MqV12Xa8ElnmBt4TwdY:b-7yulx8) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/memory/Slab.h#L56)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Since we use your trick with `currentTier()`, do we need the different types for `TierId` and `PoolId`
</blockquote></details>

Why?

**Review by vinser52 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 9 unresolved discussions (waiting on @guptask and @igchor)

___
*[cachelib/allocator/CacheAllocator.h, line 629 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU6vqZ6s8XESbaspkd:-MqZEd_5EYDIeizW5e4T:blhxjzf) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L629)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, this can be called by the user so I think this is still relevant - should this function shrink pool on specific tier or on all tiers at once?
</blockquote></details>

I would say that this function should shrink all tiers according to the ratio defined by tiers config. There are two reasons I have in mind:
1. This function shrinks the pool and pool logically spread across tiers.
2. In case we want to shrink a particular tier caller (user or background thread) should specify tierId explicitly. For that purpose, we need a separate overload.

If we keep it in such a way just for benchmarking purposes and going to implement overloads for per-tier shrinking in the future I am fine. 
___
*[cachelib/allocator/CacheAllocator.h, line 640 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU7MLe04owW9UBtiuZ:-MqZIC_l82WDQrYh4ol1:bmxczp1) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L640)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

The same as above
___
*[cachelib/allocator/CacheAllocator.h, line 1754 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8JCSBbPFTL94WjI4:-MqZG2GY3lA2-LuLqfRb:b-qkavcc) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1754)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, this function is used for methods which can be called by a user/background workers where use/bg worker must have per-tier knowledge. This is the problem I raised some time ago: how we can expose the statistics/operations for different tiers.

There is no good answer for that right now, so for this PR I have not implemented this correctly (this is not really needed for benchmarks, unless we are relying on bg workers).

I have this hack implementation which allows setting currentTier by user/bg worker but this is not needed for corectness for now (at least I think so)
</blockquote></details>

I got your point that for benchmarking purpose the BG workers are not important. But what you mean under "his function is used for methods which can be called by a user" my understanding think that if user calls some method it should be applied to all tiers or user have to specify tier explicitly.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3169 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBPDH6iOkfYlnYal0:-MqZHQQm379RY1PYTu4X:bn303s) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3169)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, most probably, but this is not so critical I believe - this is for serialization.
</blockquote></details>

Got it, let's add TODO comment at least/
___
*[cachelib/allocator/memory/Slab.h, line 56 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBr1PCEIcuRovx5Pu:-MqZIKCvAGw5AahSs6KQ:b-5skkrj) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/memory/Slab.h#L56)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why? 
</blockquote></details>

maybe I do not understand which overloads did you mean. Can you provide an example?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: 9 of 18 files reviewed, 9 unresolved discussions (waiting on @guptask, @igchor, and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 1676 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8GBo2M-kyA6VDSr6:-Mq_I8Ri2Q-bqxt-Q1kA:bip7azj) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1676)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we fix this TODO.
</blockquote></details>

Done. (kind of, this is very hacky)
___
*[cachelib/allocator/CacheAllocator.h, line 1754 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU8JCSBbPFTL94WjI4:-MqZrKRy7dg3-QA0OEXf:bz7cd6y) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L1754)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I got your point that for benchmarking purpose the BG workers are not important. But what you mean under "his function is used for methods which can be called by a user" my understanding think that if user calls some method it should be applied to all tiers or user have to specify tier explicitly.
</blockquote></details>

Yes, that's why there this TODO - basically each method which uses this function needs to be either changed to work on all tiers or accept additional tierId parameter.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: 7 of 18 files reviewed, 8 unresolved discussions (waiting on @guptask and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 629 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqU6vqZ6s8XESbaspkd:-MqnrE3mEb91RGqEoOkI:b-aeobxd) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator.h#L629)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I would say that this function should shrink all tiers according to the ratio defined by tiers config. There are two reasons I have in mind:
1. This function shrinks the pool and pool logically spread across tiers.
2. In case we want to shrink a particular tier caller (user or background thread) should specify tierId explicitly. For that purpose, we need a separate overload.

If we keep it in such a way just for benchmarking purposes and going to implement overloads for per-tier shrinking in the future I am fine. 
</blockquote></details>

That's the plan - I extended comment in currentTier()
___
*[cachelib/allocator/CacheAllocator-inl.h, line 3169 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBPDH6iOkfYlnYal0:-MqnrctoAdSoNIaQSdii:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/CacheAllocator-inl.h#L3169)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Got it, let's add TODO comment at least/
</blockquote></details>

Done.
___
*[cachelib/allocator/memory/Slab.h, line 56 at r4](https://reviewable.io/reviews/pmem/cachelib/12#-MqUBr1PCEIcuRovx5Pu:-MqnsCl48yEf3ugMEL07:b8olewf) ([raw file](https://github.com/pmem/cachelib/blob/ca27866a1a8ef02ca82a47eb07e2bf38bdf25249/cachelib/allocator/memory/Slab.h#L56)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

maybe I do not understand which overloads did you mean. Can you provide an example?
</blockquote></details>

Sorry, I forgot I put this comment there ;d Actually you are right, it is not necessary to have different types anymore. It;s only needed where we would have a function like get_stats(PoolId, TierId tid); get_stats(PoolId, SlabId slabId) or something.

**Review by vinser52 — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 2 of 11 files at r7, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 3 unresolved discussions (waiting on @guptask)

**Comment by vinser52** [comment]
I am confused that the build still failed.

**Review by vinser52 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/12)* status: all files reviewed, 3 unresolved discussions (waiting on @guptask)

**Comment by igchor** [comment]
All changes integrated into: https://github.com/pmem/CacheLib/pull/21

**Pull request closed without merging**
