### PR TITLE
Added per pool per class used size metrics

### PR DESCRIPTION
**Pull request by guptask**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/61)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
@guptask could you please describe how this new statistic compares against different stats?
- fragmentationSize
- allocAttempts/allocFailed/itemEvictions?
- getPool(poolId1).getPoolSize()

I'd like us to have some rationale for adding this change: would be great if we could show that it's not possible to get this info from other stats. For example, could we have the same info from `(allocAttempts - allocFailed) - regularItemsEvictions`? If no, why not?

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/61#-:-N-XM25I29_X2gukiqLY:b-ltbdud)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[cachelib/cachebench/cache/Cache-inl.h, line 464 at r1](https://reviewable.io/reviews/pmem/cachelib/61#-N-XN8pB-8ILL12HlJ8y:-N-XN8pB-8ILL12HlJ8z:b-coe35m) ([raw file](https://github.com/pmem/cachelib/blob/1395175d0d06c9bae660fa3ab7ced2aa8694a33d/cachelib/cachebench/cache/Cache-inl.h#L464)):*
> ```objc
>   ret.allocFailures = cacheStats.allocFailures;
> 
>   ret.poolUsedSize.swap(cacheStat.poolUsedSize);
> ```

why not `=`?

**Comment by guptask** [comment]
This per pool size statistics reports the current size of each memory pool. Existing implementation does not report this statistic, specifically:
1. fragmentation size statistic tracks fragmentation loss due to bad allocation - it is used to trigger increase in alloc size if configured to do so.
2. getPool statistics reports the total capacity for each pool - it is useful to track whether a particular pool capacity grew or shrunk.
3. allocation statistics does not track allocation per slab - so it cannot be used to calculate the size of a particular memory pool

**Review by igchor — COMMENTED** [review]
@guptask I don't get this comment: "allocation statistics does not track allocation per slab - so it cannot be used to calculate the size of a particular memory pool". Why does it matter that it does not track memory per-slab. We are only interested in used memory for particular memory pool, allocation class and (for hetero-memory version) tier, right?

Why can't we use something like:  `(allocAttempts - allocFailed) - regularItemsEvictions`?

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/61#-:-N-XM25I29_X2gukiqLY:b9ozmjg)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @guptask and @vinser52)

**Review by victoria-mcgrath — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/61)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @guptask and @vinser52)

**Pull request closed without merging**
