### PR TITLE
Async eviction

### PR DESCRIPTION
**Pull request by vinser52**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 1803 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRoa7E5pNOQLK9muf:-MpkRoa7E5pNOQLK9mug:b-ucn76) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1803)):*
> ```objc
>                                                                    // waiters
>   };
>   using MoveMap = folly::F14ValueMap<folly::StringPiece, std::unique_ptr<MoveCtx>, folly::HeterogeneousAccessHash<folly::StringPiece>>;
> ```

Why not use some concurrent map from folly instead of sharding? 
___
*[cachelib/allocator/CacheAllocator.h, line 1941 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkQAYh8krnIZKlXoNi:-MpkQAYh8krnIZKlXoNj:b-je3qus) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1941)):*
> ```objc
> 
>   static constexpr size_t kShards = 8192; // TODO: need to define right value
>   
> ```

unnecessary whitespace
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1108 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MplKEcn4fGLu-Y8QbnJ:-MplKEcoDTMlAUTRdK1D:bjnbimy) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1108)):*
> ```objc
> 
> template <typename CacheTrait>
> bool CacheAllocator<CacheTrait>::addWaitContextForMovingItem(
> ```

So, right now, on find if element is not ready we register a waiter and once item is moved between tiers and access container is updated the waiter is waken up? I think it should be described somewhere in comment (make next to a movesMap_ declaration?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1109 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRQH96JfSKzA_Q0AO:-MpkQtlb88XzdUIcBHge:bzhfr1s) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1109)):*
> ```objc
> template <typename CacheTrait>
> bool CacheAllocator<CacheTrait>::addWaitContextForMovingItem(
>   folly::StringPiece key,
> ```

please align function parameter similarly as in other functions (here and in rest of the methods)
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1152 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MplKmgG88nTazDUUPLb:-MplKmgG88nTazDUUPLc:b-10ch6b) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1152)):*
> ```objc
>     auto res = movesMap.try_emplace(key, std::make_unique<MoveCtx>());
>     if(!res.second) {
>       return false;
> ```

If this is false, there is already some other move in progress - this can happen only if there are several concurrent calls to tryEvictToNextMemoryTier, right? In that case, can't we just fail earlier by e.g. checking the notReady flag?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1160 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-Mpkmp4a89CFZK-YT5WT:-Mpkmp4a89CFZK-YT5WU:b-t7epoc) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1160)):*
> ```objc
>   auto guard = folly::makeGuard([key, this, ctx, shard, &resHdl]() {
>       auto& movesMap = getMoveMapForShard(shard);
>       resHdl->unmarkNotReady();
> ```

Is it correct? From Handle.h : `It's a bug to set a hdl that's already ready and can
    // terminate the application.` and if I understand correctly `set` is called when we do movesMap.erase(key); (so after marking resHndl as ready)

... or this notReady has nothing to do with isReady() method? if so, I would suggest renaming this
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1196 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkeaDy1nyX7hSnmAWs:-MpkeaDy1nyX7hSnmAWt:b-neteyx) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1196)):*
> ```objc
>     config_.moveCb(oldItem, *newItemHdl, nullptr);
>   } else {
>     std::memcpy(newItemHdl->getWritableMemory(), oldItem.getMemory(), oldItem.getSize());
> ```

I think we should not have a default fallback - in my opinion, we should require having moveCb set by the user. It can still be a regular memcpy but it should be explicit. Otherwise, we will break current behavior which guarantees that items are not moved without any synchronization with the user.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1512 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpknNNx-VhNnlrvLw0a:-MpknNNx-VhNnlrvLw0b:bafpgxy) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1512)):*
> ```objc
>         return acquire(&item);
>       }
>       // TODO: should we free the newItemHdl if moveRegularItemOnEviction returns false???
> ```

I think so
___
*[cachelib/allocator/Handle.h, line 471 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkoOKP72XuA021fqyH:-MpkoOKP72XuA021fqyI:b-7yaja7) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/Handle.h#L471)):*
> ```objc
>       waitContext_ = std::make_shared<ItemWaitContext>(alloc);
>       if(!alloc_->addWaitContextForMovingItem(it->getKey(), waitContext_)) {
>         waitContext_.reset();
> ```

why do you need this reset?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 1803 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRoa7E5pNOQLK9muf:-MplzlIL-RjO_Q4bxKs8:b-vaugyp) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1803)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why not use some concurrent map from folly instead of sharding? 
</blockquote></details>

It was my initial idea. But folly::ConcurrentHashMap does not provide an interface that allows to modify mapped value in place. In our use case, we need to add waiters to the MoveCtx. But find method returns only a const iterator. There is `assign` method that allows to replace existing mapped value with the new one - it is not what we need as well.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1108 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MplKEcn4fGLu-Y8QbnJ:-Mpm-iqO0nQ1g_x9-JWs:bghrpbq) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1108)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

So, right now, on find if element is not ready we register a waiter and once item is moved between tiers and access container is updated the waiter is waken up? I think it should be described somewhere in comment (make next to a movesMap_ declaration?
</blockquote></details>

The logic is the following.
The thread which moves Item:
1. Create `MoveCtx` and put it to the `movesMap`.
2. Updates the access container with the new item from the tier we are moving to. This Item has `kNotReady` flag set.
3. Copy data from the old Item to the new one.
4. Unset  the`kNotReady` flag and Notify `MoveCtx`

Concurrent threads which are getting handle to the same key:
1. When a handle is created it checks if the `kNotReady` flag is set
2. If so, Handle implementation creates waitContext and adds it to the `MoveCtx` by accessing `movesMap`.
3. Wait until the moving thread will complete its job.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator.h, line 1941 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkQAYh8krnIZKlXoNi:-Mppo0ST08V5oksu3lB7:ba3dfob) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1941)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

unnecessary whitespace
</blockquote></details>

Removed
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1108 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MplKEcn4fGLu-Y8QbnJ:-MppYTpn7mROsVnpyylr:b-70lrqt) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1108)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

The logic is the following.
The thread which moves Item:
1. Create `MoveCtx` and put it to the `movesMap`.
2. Updates the access container with the new item from the tier we are moving to. This Item has `kNotReady` flag set.
3. Copy data from the old Item to the new one.
4. Unset  the`kNotReady` flag and Notify `MoveCtx`

Concurrent threads which are getting handle to the same key:
1. When a handle is created it checks if the `kNotReady` flag is set
2. If so, Handle implementation creates waitContext and adds it to the `MoveCtx` by accessing `movesMap`.
3. Wait until the moving thread will complete its job.
</blockquote></details>

I have added comment.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1109 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRQH96JfSKzA_Q0AO:-MppW-LfA3ZzSwB4FCxM:bb6un1j) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1109)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please align function parameter similarly as in other functions (here and in rest of the methods)
</blockquote></details>

Done
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1152 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MplKmgG88nTazDUUPLb:-Mppo9WL70LWhAyrAXVj:bviylpi) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1152)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

If this is false, there is already some other move in progress - this can happen only if there are several concurrent calls to tryEvictToNextMemoryTier, right? In that case, can't we just fail earlier by e.g. checking the notReady flag?
</blockquote></details>

`notReady` flag is set for the new Item (we are moving to). At this point, we have not updated `accessContainer` yet, because before updating `accessContainer` we need to create `MoveCtx` and put it to `movesMap`.  When we updating `accessContainer` the new Item become visible to other threads. Concurrent threads that access the new Item should create `waitContext` and add it to corresponding `MoveCtx`.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1196 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkeaDy1nyX7hSnmAWs:-MpppWLvDDzBNWLCvKzr:b-ptriu6) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1196)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we should not have a default fallback - in my opinion, we should require having moveCb set by the user. It can still be a regular memcpy but it should be explicit. Otherwise, we will break current behavior which guarantees that items are not moved without any synchronization with the user.
</blockquote></details>

Should we add some checks to config if multiple tiers are configured but the callback is not set?
___
*[cachelib/allocator/Handle.h, line 471 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkoOKP72XuA021fqyH:-MppmuKw3ew_q165YR4w:bxqzvhx) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/Handle.h#L471)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

why do you need this reset?
</blockquote></details>

The `addWaitContextForMovingItem()` returns `false` if the concurrent thread that do eviction already done and destroyed MoveCtx and cleaned up the `movesMap`. It means that we cannot register `waitContext` so we should just destroy it.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 1512 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpknNNx-VhNnlrvLw0a:-Mpprfe84tBEAZT6QZP2:b-knuon0) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1512)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think so
</blockquote></details>

I just check the code. The destructor of `HandleImpl`calls `reset()` method which call `void CacheAllocator<CacheTrait>::release(Item* it, bool isNascent)` method. In case refcount to the Item is 0 the `releaseBackToAllocator()` method is called. So, I think we should not do anything in that case. Are you agree?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 1160 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-Mpkmp4a89CFZK-YT5WT:-MppsctT6XARNoUVerdi:b8gnv1y) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1160)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Is it correct? From Handle.h : `It's a bug to set a hdl that's already ready and can
    // terminate the application.` and if I understand correctly `set` is called when we do movesMap.erase(key); (so after marking resHndl as ready)

... or this notReady has nothing to do with isReady() method? if so, I would suggest renaming this
</blockquote></details>

Yeah, I think naming is confusing in this case. The method you are referring is related to waitContext of the Handle object while `isNotRedy` flag is set to the Item - it indicates that Item is not ready when new Handle by concurrent thread is creted.

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1106 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-MpsqDma4N0LqTof2z4R:-MpsqDma4N0LqTof2z4S:buro740) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1106)):*
> ```objc
> /* Next two methods are used to asynchronously move Item between memory tiers.
>  *
>  * The thread, which moves Item allocate, new Item in the tier we are moving to
> ```

Should comma go before "allocate"?

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1109 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-MpsqVil52RbQXBvbQMi:-MpsqVil52RbQXBvbQMj:b-ns9yju) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1109)):*
> ```objc
>  * and calls moveRegularItemOnEviction() method. This method does the following:
>  *  1. Create MoveCtx and put it to the movesMap.
>  *  2. Updates the access container with the new item from the tier we are
> ```

"Update"? For consistency with the rest of the bullets.

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1113 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-Mpsqg4t9qGUQHH7GBir:-Mpsqg4t9qGUQHH7GBis:bvm20ek) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1113)):*
> ```objc
>  *  3. Copy data from the old Item to the new one.
>  *  4. Unset thekNotReady flag and Notify MoveCtx
>  * 
> ```

Extra spaces.

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1106 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-MpsqDma4N0LqTof2z4R:-Mpst8rP3z-XpFIIF9v7:b3q11u1) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1106)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

Should comma go before "allocate"?
</blockquote></details>

"allocates"

**Comment by victoria-mcgrath** [comment]
___
*[cachelib/allocator/CacheAllocator.h, line 1803 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRoa7E5pNOQLK9muf:-MpstRpn-vhxtUiDaw_B:b-g7fl92) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1803)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

It was my initial idea. But folly::ConcurrentHashMap does not provide an interface that allows to modify mapped value in place. In our use case, we need to add waiters to the MoveCtx. But find method returns only a const iterator. There is `assign` method that allows to replace existing mapped value with the new one - it is not what we need as well.
</blockquote></details>

Is extending an existing class an option?

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: all files reviewed, 5 unresolved discussions (waiting on @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 1160 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-Mpkmp4a89CFZK-YT5WT:-MpvkRQT4m9TFE9bW0Z7:by6m2mx) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1160)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Yeah, I think naming is confusing in this case. The method you are referring is related to waitContext of the Handle object while `isNotRedy` flag is set to the Item - it indicates that Item is not ready when new Handle by concurrent thread is creted.
</blockquote></details>

I see, so maybe something like markNotVisible or markIncomplete?
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1196 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkeaDy1nyX7hSnmAWs:-MpqRlLC9K87r7-kafyF:b-zbmmdh) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1196)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we add some checks to config if multiple tiers are configured but the callback is not set?
</blockquote></details>

Yeah, I think so, we could just throw an error in that case
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1512 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpknNNx-VhNnlrvLw0a:-Mpvl72zDXXd8vyrQqr9:b3lbvog) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1512)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I just check the code. The destructor of `HandleImpl`calls `reset()` method which call `void CacheAllocator<CacheTrait>::release(Item* it, bool isNascent)` method. In case refcount to the Item is 0 the `releaseBackToAllocator()` method is called. So, I think we should not do anything in that case. Are you agree?
</blockquote></details>

Ok, makes sense, what about the case where we managed to insert the item into accessContainer but failed updating MMContainer? WHat should happen with such element?

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 1196 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkeaDy1nyX7hSnmAWs:-Mq-EuIiACo__b7CLWnC:b-7p08y4) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1196)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yeah, I think so, we could just throw an error in that case
</blockquote></details>

I am thinking that it is not an easy question. For example, eviction (when we campletly remove Item from the cache) provides callback option that user can set to be notified when an Item is evicted from the cache. But this callback is not mandatory. So now I do not see significant difference between moving Item between tiers and eviction from the cache.

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/16)* status: 7 of 14 files reviewed, 5 unresolved discussions (waiting on @igchor and @victoria-mcgrath)

___
*[cachelib/allocator/CacheAllocator.h, line 1803 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpkRoa7E5pNOQLK9muf:-MqKeZBrEL77R6YSJwdC:b-tribem) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator.h#L1803)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

Is extending an existing class an option?
</blockquote></details>

I believe it was designed in such a way to address possible concurrency issues. Adding a new interface will require changing the implementation.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1160 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-Mpkmp4a89CFZK-YT5WT:-MqKfqsc7wtMPZuoDOi5:bmt0u3z) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1160)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I see, so maybe something like markNotVisible or markIncomplete?
</blockquote></details>

possibly "Incomplete" is a better choice. Because Item is visible (and it is our intention) but data not copied from the old location yet.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1512 at r3](https://reviewable.io/reviews/pmem/cachelib/16#-MpknNNx-VhNnlrvLw0a:-MqKiR3B4AQh9vqng314:b-eylf77) ([raw file](https://github.com/pmem/cachelib/blob/78eed166315816d4874dc8d99ffc0828fe7d33df/cachelib/allocator/CacheAllocator-inl.h#L1512)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, makes sense, what about the case where we managed to insert the item into accessContainer but failed updating MMContainer? WHat should happen with such element?
</blockquote></details>

In that case, Item is removed from the accessContainer by the `moveRegularItemOnEviction` method.
I have removed TODO comment
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1106 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-MpsqDma4N0LqTof2z4R:-MqKfL0p11SQtXRmEzbQ:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1106)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

"allocates"
</blockquote></details>

Done.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1109 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-MpsqVil52RbQXBvbQMi:-MqKfOSy5Oqf-v4xCLda:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1109)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

"Update"? For consistency with the rest of the bullets.
</blockquote></details>

Done.
___
*[cachelib/allocator/CacheAllocator-inl.h, line 1113 at r7](https://reviewable.io/reviews/pmem/cachelib/16#-Mpsqg4t9qGUQHH7GBir:-MqKfmfD7yLUoAN0Qk5o:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/043183754e2894bfe3de16d9a542c0420c34e1f9/cachelib/allocator/CacheAllocator-inl.h#L1113)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

Extra spaces.
</blockquote></details>

Done.

**Comment by igchor** [comment]
Changes already merged into develop.

**Pull request closed without merging**
