### PR TITLE
Minimal changes to cache config API to initiate introduction of multi-tier cache configuration

### PR DESCRIPTION
**Pull request by victoria-mcgrath**
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/64)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
@victoria-mcgrath should we also add some tests/examples to this PR?

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/64#-:-N0VdSLFDWMkc1dAp3vw:b-boncgh)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @guptask and @victoria-mcgrath)

___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 865 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VdIUR2_0p9xy2wYbc:-N0VdIUR2_0p9xy2wYbd:bex766) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L865)):*
> ```objc
>         "Posix shm can be set only when cache persistence is enabled");
>   }
>   usePosixShm = true;
> ```

do we still need this variable? perhaps we could add some function like isPosixShm() which would just check the memory tiers vector?
___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 867 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VaGtH8cLJvKtIRo1j:-N0VaGtH8cLJvKtIRo1k:b4xzkza) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L867)):*
> ```objc
>   usePosixShm = true;
>   return setUsePosixForTiers();
>   ;
> ```

unnecessary `;`
___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 890 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VcoQVEx4N7WSbPlog:-N0VcoQVEx4N7WSbPloh:bgydstz) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L890)):*
> ```objc
>     const MemoryTierConfigs& config) {
>   if (config.size() > 1) {
>     std::system_error("Only single memory tier is currently supported.");
> ```

missing `throw`? Also what about empty vector?
___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 930 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VaiyV3daLU_gYyRH9:-N0VaiyV3daLU_gYyRHA:bvvv2h0) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L930)):*
> ```objc
>         sumSizes += tierConfig.getSize();
>       }
>       if (getCacheSize() != sumSizes) {
> ```

I'm actually not sure if we should add this extra space to the last tier: this resulted in some problems as I remember: https://github.com/pmem/CacheLib/issues/44
https://github.com/pmem/CacheLib/commit/02a3bfbf9b1db8cf8fe904cabe7bfd23261d81ee
___
*[`cachelib/allocator/MemoryTierCacheConfig.h` line 64 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0Vd61J1MIZazGV1e69:-N0Vd61J1MIZazGV1e6A:b-pzlj6y) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/MemoryTierCacheConfig.h#L64)):*
> ```objc
>   // tier. E.g. if X is a total cache size, Yi are ratios specified for memory
>   // tiers, then size of the i-th tier Xi = (X / (Y1 + Y2)) * Yi and X = sum(Xi)
>   size_t ratio{0};
> ```

Recently, I realized that `weight` might be a better name than `ration`. What do you think?

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/MemoryTierCacheConfig.h` line 64 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0Vd61J1MIZazGV1e69:-N0WJlH5AVCCab6-RRjI:beqm6bo) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/MemoryTierCacheConfig.h#L64)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Recently, I realized that `weight` might be a better name than `ration`. What do you think?
</blockquote></details>

I am not sure about "weight" (it usually is used to adjust an existing value). What do you think about "share", "part", "partition", "quota"?

**Comment by victoria-mcgrath** [comment]
*[`cachelib/allocator/CacheAllocatorConfig.h` line 865 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VdIUR2_0p9xy2wYbc:-N0WLYBC84xnxrr-K31T:b-qdpxn7) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L865)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

do we still need this variable? perhaps we could add some function like isPosixShm() which would just check the memory tiers vector?
</blockquote></details>

I will double check but I thought the mainstream version of cachelib required it. New method - point taken.

**Review by victoria-mcgrath — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/64)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @guptask and @igchor)

___
*[`cachelib/allocator/CacheAllocatorConfig.h` line 890 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0VcoQVEx4N7WSbPlog:-N0WMhky5ONzN4DUw9dt:b-896fix) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/CacheAllocatorConfig.h#L890)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

missing `throw`? Also what about empty vector?
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/64#-:-N0l1mQj5D7k2x1zftCZ:bnfp4nl)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @guptask and @igchor)

___
*[`cachelib/allocator/MemoryTierCacheConfig.h` line 64 at r1](https://reviewable.io/reviews/pmem/cachelib/64#-N0Vd61J1MIZazGV1e69:-N0l1N3i8XdDsuuZNIrM:b-gzib6z) ([raw file](https://github.com/pmem/cachelib/blob/3f9d8f2e5a25db7e0c311ea9898e9dfd8dc76b30/cachelib/allocator/MemoryTierCacheConfig.h#L64)):*
<details><summary><i>Previously, victoria-mcgrath wrote…</i></summary><blockquote>

I am not sure about "weight" (it usually is used to adjust an existing value). What do you think about "share", "part", "partition", "quota"?
</blockquote></details>

'share' sounds pretty good. But we might also leave to the Meta guys to decide

**Pull request closed without merging**
