### PR TITLE
Publish changes from innersouce

### PR DESCRIPTION
**Pull request by igchor**

### CODE REVIEW

**Review by guptask — APPROVED** [review]
I think we can merge it without review since these changes have already been reviewed before merge into inner-source main. The commit history looks ok.

**Comment by vinser52** [comment]
Should we keep commits for self-hosted runners?

**Comment by igchor** [comment]
I can manually squash all those self-hosted runners commits to just a single one. @vinser52 would that be ok?

In general, we probably want the self-hoster runners change to be present on develop branch.

**Comment by igchor** [comment]
I can also clear up the history by removing the merge commits.

**Comment by igchor** [comment]
Here's PR with cleared history: https://github.com/pmem/CacheLib/pull/3

I've also extended description of one commit from @guptask (regarding key serialization) to have some useful info.

**Pull request closed without merging**
