### PR TITLE
2Q iterator starting from hot queue

### PR DESCRIPTION
**Pull request by byrnedj**
rebased on to develop and added some tests.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/97)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/97#-:-N7zo8zJ5wptFsgenf0X:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`cachelib/allocator/datastruct/MultiDList.h` line 115 at r1](https://reviewable.io/reviews/pmem/cachelib/97#-N7zmEBvB5SZN3sWP4BV:-N7zmEBvB5SZN3sWP4BW:b-3l7qzq) ([raw file](https://github.com/pmem/cachelib/blob/cb862f72525c9b6c3ab759f6505a480dcc1bb865/cachelib/allocator/datastruct/MultiDList.h#L115)):*
> ```objc
>                       size_t listIdx) noexcept
>         : currIter_(mlist.lists_[mlist.lists_.size() - 1]->rbegin()),
>           mlist_(mlist) {
> ```

you could probably just call the ctor you crated with head == false, no?
___
*[`cachelib/allocator/datastruct/MultiDList.h` line 134 at r1](https://reviewable.io/reviews/pmem/cachelib/97#-N7zm67H-CYSwv03Dcuk:-N7zm67I2iriaqOOpgj-:byhnojb) ([raw file](https://github.com/pmem/cachelib/blob/cb862f72525c9b6c3ab759f6505a480dcc1bb865/cachelib/allocator/datastruct/MultiDList.h#L134)):*
> ```objc
>       // We should either point to an element or the end() iterator
>       // which has an invalid index_.
>       XDCHECK(index_ == kInvalidIndex || index_ == mlist.lists_.size() || currIter_.get() != nullptr);
> ```

nit: this could be moved under the if above so that we can assert exactly the state we want

**Review by byrnedj — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/97)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @igchor)

___
*[`cachelib/allocator/datastruct/MultiDList.h` line 115 at r1](https://reviewable.io/reviews/pmem/cachelib/97#-N7zmEBvB5SZN3sWP4BV:-N91fAeK-beZV5G1JYCe:b-9f087b) ([raw file](https://github.com/pmem/cachelib/blob/cb862f72525c9b6c3ab759f6505a480dcc1bb865/cachelib/allocator/datastruct/MultiDList.h#L115)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

you could probably just call the ctor you crated with head == false, no?
</blockquote></details>

Yep, done.
___
*[`cachelib/allocator/datastruct/MultiDList.h` line 134 at r1](https://reviewable.io/reviews/pmem/cachelib/97#-N7zm67H-CYSwv03Dcuk:-N91f-Xl85-kEOAY809D:b-z6g9b8) ([raw file](https://github.com/pmem/cachelib/blob/cb862f72525c9b6c3ab759f6505a480dcc1bb865/cachelib/allocator/datastruct/MultiDList.h#L134)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

nit: this could be moved under the if above so that we can assert exactly the state we want
</blockquote></details>

We need to check the index_ after it's been initialized in initToValid(R)BeginFrom().

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/97#-:-N91ff5I1gIS3m_moOWJ:bnfp4nl)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @igchor)

**Comment by igchor** [comment]
@byrnedj Can you create PR against intel/CacheLib?

**Comment by igchor** [comment]
Merged to intel/CacheLib

**Pull request closed without merging**
