### PR TITLE
Allocate in first available tier

### PR DESCRIPTION
**Pull request by igchor**
and evict only from the bottom tier.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)

### CODE REVIEW

**Review by vinser52 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-MyqwP3XBsjqneAW4mgn:b-s8a2ll) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
> ```objc
>   // TODO: Today disableEviction means do not evict from memory (DRAM).
>   //       Should we support eviction between memory tiers (e.g. from DRAM to PMEM)?
>   if (memory == nullptr && tid < numTiers_ - 1) {
> ```

As we agreed during our call, let's add config option to control this behavior.

**Review by vinser52 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-MyqwsK_4qKB_6lGjafZ:bm2hr0v) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

As we agreed during our call, let's add config option to control this behavior.
</blockquote></details>

Also `allocateInternalTier()` called in a loop from several places. Need to decide how to implement the proposed approach in the right way.

**Review by vinser52 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @igchor and @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-MyrQkrd7nOg2H_T0EzY:b-n2dhuk) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done - I extended the config.

As for calling it in a loop, we could perhaps just remove those loops
</blockquote></details>

Right now with your changes, we have recursion in the `allocateInternalTier` function - it can be considered as a replacement for the loop. But the behavior of the `allocateInternalTier` function might be misleading. Imagine the following:
* The `allocateInternalTier` called with `tid = 0`.
* Tier 0 is full and we recursively call the `allocateInternalTier` function with `tid = 1`.
* When we successfully allocated `Item` from Tier 1, we return it recursively to the initial caller. And it might be confusing, initially caller asked for allocation from tier 0, but returned Item was allocated in tier 1.

Described case is important for eviction when we allocate destination `Item` using `allocateInternalTier`.

Let's try to figure out the right design on our 1-1 tomorrow.

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-Myw2Qt89c9tWZ7vnx4L:b-5zp51f) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Right now with your changes, we have recursion in the `allocateInternalTier` function - it can be considered as a replacement for the loop. But the behavior of the `allocateInternalTier` function might be misleading. Imagine the following:
* The `allocateInternalTier` called with `tid = 0`.
* Tier 0 is full and we recursively call the `allocateInternalTier` function with `tid = 1`.
* When we successfully allocated `Item` from Tier 1, we return it recursively to the initial caller. And it might be confusing, initially caller asked for allocation from tier 0, but returned Item was allocated in tier 1.

Described case is important for eviction when we allocate destination `Item` using `allocateInternalTier`.

Let's try to figure out the right design on our 1-1 tomorrow.
</blockquote></details>

Done. I move the logic which decides whether to evict or not to upper layers. What do you think?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-Myw2ck57F4diIUE1gk6:b-4kitz6) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done. I move the logic which decides whether to evict or not to upper layers. What do you think?
</blockquote></details>

We might think about parametrizing the evict value in tryEvictToNextMemoryTier also

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-Myw7Ahw264isdscfiBo:b-dc4lm0) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

We might think about parametrizing the evict value in tryEvictToNextMemoryTier also
</blockquote></details>

Also, should we move latencyTracker to the upper layers? With current approach we will have more data points (when if (memory == nullptr && !evict) branch is taken).

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/cachelib/55)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[cachelib/allocator/CacheAllocator-inl.h, line 377 at r1](https://reviewable.io/reviews/pmem/cachelib/55#-MyqwP3XBsjqneAW4mgm:-MzQ92T698rGJzOO_iea:bso4pt7) ([raw file](https://github.com/pmem/cachelib/blob/ee3bb6b92e64aff7003ce7ed9bbb5ead620c064d/cachelib/allocator/CacheAllocator-inl.h#L377)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Also, should we move latencyTracker to the upper layers? With current approach we will have more data points (when if (memory == nullptr && !evict) branch is taken).
</blockquote></details>

Ok, I actually tries moving this latency tracker to upper layer but it did not change the reported latency much. I belive we can leave it as is.

**Pull request closed without merging**
